Adventures: refactor create/edit and add success/error alerts
kernel-community/services pull request #3
Opened 2022-05-23 16:01 UTC by rorysaur

+ Extracts Create/Edit into a shared ProjectForm component
+ Extracts `components` into a constants file
+ Adds success/error alerts on create and edit

<img width="639" alt="Screen Shot 2022-05-23 at 11 52 24 AM" src="https://user-images.githubusercontent.com/4686089/169860417-b7e3545a-9d80-4c8e-9971-dcdb9a89f242.png">

2022-05-23 16:03 UTC, rorysaur commented on packages/projects/src/components/ProjectForm.jsx
> +import { components } from 'constants.js'
There is some bug/issue with standard.js where it won't let me just import from `'constants'` even though it works. It thinks it is some sort of reserved module name.

2022-05-24 16:05 UTC, simonkernel requested changes
Thanks @rorysaur for working on this much needed improvement for the adventures page!

Only a few minor things I'd like you to consider :pray: 

I'll look forward to merging these changes shortly!

2022-05-24 17:56 UTC, rorysaur commented on packages/common/src/components/Navbar.jsx
> +            {title &&
oh, this adds `className={textColor}` because I noticed it wasn't being applied here

2022-05-24 17:56 UTC, rorysaur commented on packages/projects/src/components/ProjectForm.jsx
> +    data.url = urlPlaceholder
So I felt the same, so I tried just setting `url`, but then if it auto-generates on `title` change, and if you go and edit the `url` and then edit the `title` after, it overwrites it again. Which also seemed surprising/annoying.

The ideal logic would be "Don't change the URL anymore if the user has already touched it" but that seemed too complicated to worry about in the moment. (But I think I know how to do it now so I can try and see.)

2022-05-24 17:56 UTC, rorysaur commented on packages/projects/src/components/ProjectForm.jsx
> +    let saved
eh, it's just there to console log it on line 94 which was the existing behavior. I find that mildly helpful

2022-05-24 17:56 UTC, rorysaur commented on packages/projects/src/components/ProjectForm.jsx
> +  const allProjects = await state.projects.getAll()
ah, perfect!

2022-05-26 21:24 UTC, simonkernel approved these changes
One small nit that you can clean up with the next PR.

2022-05-26 21:24 UTC, simonkernel commented on packages/projects/src/components/ProjectForm.jsx
> +const onUrlBlur = (state, dispatch, e) => {
nit: this should be `async`

2022-05-26 21:24 UTC, simonkernel commented on packages/projects/src/components/ProjectForm.jsx
> +  validateUrl(url, state, dispatch)
nit: you should `await`.

while this works as is right now, it's going to cause an issue in the future if you extend the function.

2022-05-26 21:24 UTC, merged